### ISSUE TITLE
en_surface_forms.tsv.zip is corrupt/not downloadable

### ISSUE THREAD

**Issue by deltagreen** [dice-group/BENGAL#15]
Although the documentation states it is 119MB, each time I try to download the file, it stops at around 38MB. Could you provide an alternate url to get the file?
![Annotation 2019-12-22 123216](https://user-images.githubusercontent.com/8903122/71324602-1f3e1980-24b7-11ea-9a09-1108b79b00b1.jpg)

**Comment by DiegoMoussallem** [comment]
Hi @deltagreen, there might be a problem from your side or connection, are you just clicking on the link in the documentation? Because, here, it is downloading normally. See the picture 
<img width="234" alt="Screen Shot 2019-12-27 at 1 29 55 PM" src="https://user-images.githubusercontent.com/6675430/71517192-3a40cd00-28ad-11ea-9a61-9eee1e50ced5.png">
