### ISSUE TITLE
Add ARQ.Init() to org.aksw.simba.bengal.controller.BengalController

### ISSUE THREAD

**Issue by munnellg** [dice-group/BENGAL#9]
Using BENGAL on my system requires that ARQ be explicitly initialized before it can be used. Failure to do this results in an exception. Adding ARQ.Init() to the main function in org.aksw.simba.bengal.controller.BengalController remedies the problem

**Comment by MichaelRoeder** [comment]
1. I think there is a jena wide lifecycle definition that should be used (see https://issues.apache.org/jira/browse/JENA-1029)
2. Maybe I am wrong but as far as I know, if a jena (sub) module is not initialized, it typically means that the system has been build in the wrong way.

I would suggest to further dig into the problem and figure out what is going wrong instead of adding a static call to an initialization that might already have been called before.

**Comment by munnellg** [comment]
Admittedly, I have altered the pom slightly as noted in the other issue I opened. If you can update the README, I will revert to your pom configuration and see if that remedies the problem.

**Comment by MichaelRoeder** [comment]
The correct configuration of the shade plugin fixes the issue.
